version: '3'

services:
  web:
    build: .

    ports: ["8000:8000"]
    env_file: .env
    depends_on: [db]
    volumes: [".:/usr/src/app"]

    stdin_open: true
    tty: true

    command: gunicorn $SITE_APP_NAME.wsgi -b 0.0.0.0:$PORT --log-file - -c debug.ini

  db:
    image: postgres:latest
