# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/

version: 2

jobs:
  build:
    working_directory: /app

    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Run tests
          command: |
            docker-compose -f ./docker-compose.test.yml up
      - deploy:
          name: Push application image
          command: |
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
						docker tag app registry.heroku.com/$HEROKU_APP_NAME/web
						docker push registry.heroku.com/$HEROKU_APP_NAME/web
