# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, help_text='Optional.  Leave blank for anonymous comments.', max_length=255, null=True)),
                ('website', models.URLField(blank=True, help_text='Optional.', max_length=255, null=True)),
                ('comment', models.TextField(help_text='In markdown format.  To reply to a comment, refer to it by name and/or number.\ne.g.  "Fred #4", "David #1", "comment #11", etc.')),
                ('moderator', models.BooleanField(default=False, editable=False)),
                ('flagged', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
