# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='In markdown format. To reply to someone, refer to them by name or to their comment by number. (e.g.  "Jane #4", "John #1", "comment #11", etc.)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, help_text='Leave blank for anonymous comments.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
