# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170625_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
