# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20170625_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='flagged',
        ),
    ]
